// Source File (.cpp)
// This code was automatically generated by the Dml Editor.
#include "Demo1Translation.h"

/*static*/ const char* Demo1Translation::urn = "urn:dml:demo1";

/*static*/ PrimitiveSet Demo1Translation::RequiredPrimitiveSets[] = {
	PrimitiveSet("common", "le", "")
};

Association Demo1Translation::Solar_System::name(1, "name", PrimitiveTypes::String);
Association Demo1Translation::Solar_System::Star(2, "Star", NodeTypes::Container);
Association Demo1Translation::Solar_System::Planet::radius_in_km(3, "radius-in-km", PrimitiveTypes::Double);
Association Demo1Translation::Solar_System::Planet::Moon(4, "Moon", NodeTypes::Container);
class Demo1Translation::Solar_System::Planet Demo1Translation::Solar_System::Planet;
class Demo1Translation::Solar_System Demo1Translation::Solar_System;
