// Header File (.h)
// This code was automatically generated by the Dml Editor.

#include "../../Dml Parsing Library for C++/Dml.h"
using namespace wb::dml;

class Demo1Translation : public Translation
{
public:
	static const char* urn;

	enum { NumOfRequiredPrimitiveSets = 1 };
	static PrimitiveSet RequiredPrimitiveSets[1];

	class Solar_System : public Association {
	public:
		class Planet : public Association {
		public:
			static Association radius_in_km;
			static Association Moon;

			Planet() : Association(3, "Planet", NodeTypes::Container) {
				pLocalTranslation = new Translation();
				pLocalTranslation->Add(radius_in_km);
				pLocalTranslation->Add(Moon);
			}
		};

		static Association name;
		static Association Star;
		static Planet Planet;

		Solar_System() : Association(1, "Solar-System", NodeTypes::Container) {
			pLocalTranslation = new Translation();
			pLocalTranslation->Add(name);
			pLocalTranslation->Add(Star);
			pLocalTranslation->Add(Planet);
		}
	};

	static Solar_System Solar_System;

	Demo1Translation()
	{
		Add(Solar_System);
	}
};
